### PR TITLE
add other encoding support

### PR DESCRIPTION
**Pull request by yorkie**
hi, @jonathanong:

Can we need to add `base64` or other `encoding` to this package?
I wanna think out PEM file maybe need a base64 encoding or others.

### CODE REVIEW

**Comment by jonathanong** [comment]
Lol I tested this out and it didn't add much performance so I'm meh about it. I'll add you as collab. Do as you please :)

**Comment by yorkie** [comment]
I'm not so clear about the word `meh`, you can use more simple words to express your thoughts. sorry about my poor english, but please :(

**Comment by jonathanong** [comment]
it just means "i don't care"

**Comment by yorkie** [comment]
Sorry about this, merged :p

**Comment by jonathanong** [comment]
whats your npm name

**Comment by yorkie** [comment]
yorkie, what's wrong?

**Comment by jonathanong** [comment]
k added you as owner

**Comment by yorkie** [comment]
:p

**Pull request merged**
